# Generated by Django 3.1.10 on 2021-05-18 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_auto_20210515_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pokemon_images', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='Широта местоположения'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='longtitude',
            field=models.FloatField(null=True, verbose_name='Долгота местоположения'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_entity1', to='pokemon_entities.pokemon', verbose_name='Тип покемона'),
        ),
    ]
